"""Helper functions and fixtures for OpenShell integration tests."""

from .artifacts import (
    ensure_juju_readable,
    resolve_charm_file,
)
from .command import run_cmd
from .constants import (
    APP_NAME,
    CHARM_DIR,
    CONTAINER_NAME,
    DB_GATEWAY_APP,
    DB_HYDRA_APP,
    HYDRA_APP,
    INFRA_APPS,
    IT_GROUP,
    IT_IDENTITY,
    IT_PROJECT,
    K8S_CONTROLLER,
    LOGIN_UI_APP,
    LXD_JOIN_SECRET,
    OIDC_ADMIN_ROLE,
    OIDC_AUDIENCE,
    OIDC_ROLES_CLAIM,
    OIDC_USER_ROLE,
    REPO_ROOT,
    TLS_APP,
    TRAEFIK_APP,
)
from .juju_wait import (
    fail_on_app_error,
    gateway_status,
    is_transient_container_error,
    wait_for_gateway_stack,
    wait_for_workload_running,
)
from .kube import (
    get_traefik_lb_address,
    kubectl,
    kubectl_try,
)
from .lxd import (
    gateway_client_cert_fingerprint,
    join_gateway_to_lxd,
    lxc_instance_projects,
    put_join_secret,
    remove_join_secret,
    wait_for_gateway_message,
    wait_for_identity_trusted,
    wait_for_lxd_project,
)
from .oidc import (
    create_hydra_m2m_client,
    get_oidc_client_config,
    prepare_openshell_client,
    trust_self_signed_ca,
)
from .openshell_cli import (
    driver_help_output,
    openshell_gateway_add,
    openshell_gateway_remove,
    openshell_sandbox_create,
    openshell_sandbox_delete,
    openshell_sandbox_exec,
    openshell_sandbox_wait_running,
    openshell_status,
    run_gated_sandbox_e2e,
    sandbox_e2e_supported,
    unique_marker,
)

__all__ = [
    "APP_NAME",
    "CHARM_DIR",
    "CONTAINER_NAME",
    "DB_GATEWAY_APP",
    "DB_HYDRA_APP",
    "HYDRA_APP",
    "INFRA_APPS",
    "IT_GROUP",
    "IT_IDENTITY",
    "IT_PROJECT",
    "K8S_CONTROLLER",
    "LOGIN_UI_APP",
    "LXD_JOIN_SECRET",
    "OIDC_ADMIN_ROLE",
    "OIDC_AUDIENCE",
    "OIDC_ROLES_CLAIM",
    "OIDC_USER_ROLE",
    "REPO_ROOT",
    "TLS_APP",
    "TRAEFIK_APP",
    "create_hydra_m2m_client",
    "driver_help_output",
    "ensure_juju_readable",
    "fail_on_app_error",
    "gateway_client_cert_fingerprint",
    "gateway_status",
    "get_oidc_client_config",
    "get_traefik_lb_address",
    "is_transient_container_error",
    "join_gateway_to_lxd",
    "kubectl",
    "kubectl_try",
    "lxc_instance_projects",
    "openshell_gateway_add",
    "openshell_gateway_remove",
    "openshell_sandbox_create",
    "openshell_sandbox_delete",
    "openshell_sandbox_exec",
    "openshell_sandbox_wait_running",
    "openshell_status",
    "prepare_openshell_client",
    "put_join_secret",
    "remove_join_secret",
    "resolve_charm_file",
    "run_cmd",
    "run_gated_sandbox_e2e",
    "sandbox_e2e_supported",
    "trust_self_signed_ca",
    "unique_marker",
    "wait_for_gateway_message",
    "wait_for_gateway_stack",
    "wait_for_identity_trusted",
    "wait_for_lxd_project",
    "wait_for_workload_running",
]
